rootProject.name = "PhotoSurfer-Android"
include(":app")
include(":core")
include(":data")
include(":domain")
include(":navigator")
include(":shared")
include(":feature:push-setting")
include(":feature:register-tag")
include(":feature:auth")
include(":feature:main")
include(":feature:alarm-list")
include(":feature:search-tag")
include(":feature:search-result")
